### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by perplexes** [swamp-agr/blaze-textual#1]
$ cabal install blaze-textual
Resolving dependencies...
cabal: cannot configure blaze-textual-0.1.0.0. It requires integer-gmp -any
There is no available version of integer-gmp that satisfies -any

I am new to Haskell, and I saw some discussion around replacing integer-gmp with a BSD-licensed Integer version, like in http://www.well-typed.com/blog/32. Is this the cause of my problems?

Anyway, I need your package to install Yesod, so please let me know what I should do here.

**Comment by swamp-agr** [comment]
I think, it could be closed, see #20 for more details. :) 
Ah, and `integer-simple` supported via flag.
